# Alabaster light theme for tmux

set -g status-style "bg=#e8e8e8,fg=#000000"
set -g status-left-style "fg=#325cc0,bold"
set -g window-status-current-style "fg=#f7f7f7,bg=#325cc0,bold"
set -g pane-border-style "fg=#b7b7b7"
set -g pane-active-border-style "fg=#325cc0"
set -g message-style "bg=#325cc0,fg=#f7f7f7"
set -g mode-style "bg=#bfdbfe,fg=#000000"
