#!/bin/sh
# Set random terminal background color on SSH login

colors="32/2c/29 1e/28/3a 2d/1e/3a 3a/2e/1e 1e/3a/35"
chosen=$(echo "$colors" | tr ' ' '\n' | shuf -n 1)
printf '\e]11;rgb:%s\a' "$chosen"

# Handle X11 forwarding (required for SSH rc)
if read -r proto cookie && [ -n "$DISPLAY" ]; then
    if [ "$(echo "$DISPLAY" | cut -c1-10)" = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:"$(echo "$DISPLAY" | cut -c11-)" "$proto" "$cookie"
    else
        # X11UseLocalhost=no
        echo add "$DISPLAY" "$proto" "$cookie"
    fi | xauth -q -
fi
